@startuml
component kafka_brokers as "Kafka Brokers"
component schema_registry as "Schema Registry"
component akhq as "AKHQ"

interface jmx_exporter as "JMX Exporter"
component kafka_connect as "Kafka-Connect"
jmx_exporter -> kafka_connect

database postgresql as "PostgreSQL"
component adminer as "Adminer"

component prometheus as "Prometheus"
component grafana as "Grafana"

queue connect.orders

kafka_brokers <-- schema_registry

postgresql <-- adminer

kafka_brokers <-- kafka_connect
schema_registry <-- kafka_connect
postgresql <-- kafka_connect

akhq -up-> kafka_brokers
akhq -> schema_registry
akhq --> kafka_connect

kafka_connect --> connect.orders

jmx_exporter <-- prometheus
prometheus <-- grafana
@enduml
